POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Tech",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/694fb648-7742-4f8c-b980-d771ac97fc1a/attendees
Content-Type: application/json

{
  "name": "Emerson Rocha",
  "email": "emerson@gmail.com"
}

###

GET http://localhost:3333/events/694fb648-7742-4f8c-b980-d771ac97fc1a

###

GET http://localhost:3333/attendees/1/badge
###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/694fb648-7742-4f8c-b980-d771ac97fc1a/attendees?query=emerson