POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 11223,
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/84ccb7e4-37b3-40c5-8b09-11ef848da432/attendees
Content-Type: application/json

{
  "name": "Emerson Rocha",
  "email": "emerson80962@gmail.com"
}

###

GET http://localhost:3333/events/84ccb7e4-37b3-40c5-8b09-11ef848da432

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/3/check-in

###

GET http://localhost:3333/events/84ccb7e4-37b3-40c5-8b09-11ef848da432/attendees?query=emerson
